/**
 * Generates docs/TOOLS.md from the live tool schemas (mounted on the real DSH
 * component host) merged with src/dsh/catalog.ts. Run with `--check` to fail
 * when the committed file is out of date (CI does this).
 */
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { Context } from '@deepseek-ai/cordis'
import SkillRegistry from '@deepseek-ai/dsh-skill'
import SystemPrompt from '@deepseek-ai/dsh-system-prompt'
import ToolRuntime from '@deepseek-ai/dsh-tools'
import { DshDitto, TOOL_CATALOG, dittoSkill } from '../src/dsh/index.js'

interface JsonSchemaNode { type?: string; description?: string; enum?: unknown[]; items?: JsonSchemaNode; properties?: Record<string, JsonSchemaNode>; required?: string[] }

const OUTPUT = join(process.cwd(), 'docs', 'TOOLS.md')

async function render(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'dsh-ditto-tools-doc-'))
  try {
    const ctx = new Context()
    await ctx.plugin(SkillRegistry, {})
    await ctx.plugin(SystemPrompt, {})
    await ctx.plugin(ToolRuntime, { mode: 'native' })
    await ctx.plugin(DshDitto, { workspaceRoot: root })
    const schemas = new Map(ctx.tools.schemas().map(schema => [schema.name, schema as { name: string; description: string; parameters: JsonSchemaNode }]))
    const skill = dittoSkill()
    await ctx.fiber.dispose()

    const missing = TOOL_CATALOG.filter(fact => !schemas.has(fact.name)).map(fact => fact.name)
    const uncatalogued = [...schemas.keys()].filter(name => name.startsWith('ditto') && !TOOL_CATALOG.some(fact => fact.name === name))
    if (missing.length || uncatalogued.length) throw new Error(`Tool catalog drift. Missing registrations: ${missing.join(', ') || 'none'}. Uncatalogued tools: ${uncatalogued.join(', ') || 'none'}.`)

    const lines: string[] = []
    lines.push('# Ditto native tools', '')
    lines.push('<!-- Generated by `npm run docs:tools` from the live tool schemas and src/dsh/catalog.ts. Do not edit by hand. -->', '')
    lines.push('These tools are for the DSH agent, not for people. You do not need to remember them: the `ditto` skill routes ordinary requests such as "write specs for every module" to the right sequence. This reference exists so you can audit exactly what the agent can do, what each call writes, and where the human approval gates are.', '')
    lines.push(`Skill: \`${skill.name}\` — ${skill.description}`, '')
    lines.push('## At a glance', '')
    lines.push('| Tool | Workflow | Stage | Writes | Approval |', '|---|---|---|---|---|')
    for (const fact of TOOL_CATALOG) lines.push(`| \`${fact.name}\` | ${fact.workflow === 'spec' ? 'Code → Spec' : 'File organisation'} | ${fact.stage} | ${fact.writes} | ${fact.approval} |`)
    lines.push('')
    for (const workflow of ['spec', 'files'] as const) {
      lines.push(`## ${workflow === 'spec' ? 'Code → Spec' : 'File organisation'}`, '')
      for (const fact of TOOL_CATALOG.filter(entry => entry.workflow === workflow)) {
        const schema = schemas.get(fact.name)!
        lines.push(`### \`${fact.name}\``, '')
        lines.push(`**Purpose.** ${fact.purpose}`, '')
        lines.push(`**Stage.** ${fact.stage}`, '')
        lines.push(`**Writes.** ${fact.writes}`, '')
        lines.push(`**Approval.** ${fact.approval}`, '')
        lines.push(`**Failure cases.** ${fact.failures}`, '')
        lines.push('**Description shown to the agent.**', '', `> ${schema.description}`, '')
        lines.push('**Input.**', '')
        const properties = schema.parameters.properties ?? {}
        const required = new Set(schema.parameters.required ?? [])
        if (Object.keys(properties).length === 0) lines.push('_No parameters._', '')
        else {
          lines.push('| Parameter | Type | Required | Description |', '|---|---|---|---|')
          for (const [name, property] of Object.entries(properties)) lines.push(`| \`${name}\` | ${typeOf(property)} | ${required.has(name) ? 'yes' : 'no'} | ${(property.description ?? '').replace(/\|/g, '\\|')} |`)
          lines.push('')
        }
        lines.push('**Output.** A JSON object; the tool result is the lossless JSON rendered as text.', '')
      }
    }
    return `${lines.join('\n').trimEnd()}\n`
  } finally {
    await rm(root, { recursive: true, force: true })
  }
}

function typeOf(node: JsonSchemaNode): string {
  if (node.enum) return `enum: ${node.enum.map(value => `\`${String(value)}\``).join(', ')}`
  if (node.type === 'array' && node.items) return `array of ${node.items.type === 'object' && node.items.properties ? `{ ${Object.entries(node.items.properties).map(([key, value]) => `${key}: ${value.type ?? 'any'}`).join(', ')} }` : node.items.type ?? 'any'}`
  return node.type ?? 'json'
}

async function main(): Promise<void> {
  const content = await render()
  if (process.argv.includes('--check')) {
    const current = await readFile(OUTPUT, 'utf8').catch(() => '')
    if (current.replace(/\r\n/g, '\n') !== content) { console.error(`docs/TOOLS.md is out of date. Run: npm run docs:tools`); process.exitCode = 1; return }
    console.log('docs/TOOLS.md is up to date.')
    return
  }
  await writeFile(OUTPUT, content, 'utf8')
  console.log(`Wrote ${OUTPUT} (${TOOL_CATALOG.length} tools).`)
}

void main().catch(error => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1 })
